package main

import (
	"fmt"
)

// var sample_s string = "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"
// 20 12 17 21
var sample_s string = "CCGCACCACCGTCTACACGAAAAGGCTAGTTAAGGATCGGGACTCATCCAATGTTTCACGGGCACGAGTCATCTCGCCCTTTTTGAAATGCGCTAGTACGGGCCCAAGGTGGATCACGCCCGGGGGCTCGGAGGGGCGCAAGCACGAAGAGATAGTGCCCAGACCCATAAGAGCTTCGGATTGATAAGGACCCTTCGATCCAATGGGTGCTGCCCCTGACGGCTATGATGGGCCCGCGTATTCTTCGAGGCGGGAACAGTATCTCATTCGCCTGAGAGTCAGGTTTTTTAGACACAGCGCGTCAGTGCGGCGTTACGATCCGAAATGACTCATAGGTCGTCATTTTGCATTTACACATGAAGAGTGCCACGGAGGTCGCCTAGTGTCAACCCGGAGATGTTAGTGTAAATGCCGGCGCAGTTGGTTCACTCGTGACACCCGAATCTACGCTCTTCATATAGATAATGATCCATTCCCCCGCCTTTCTATCGTTTCCCGGGAGGCGGGTCATCCTCCGGTGGTAAGGTGAGACGCCCCTTGGACGTATGACCTTTGTGCAACTTAGCACGCGCTGAATGAATTCGTCTGATAGTATTATAATTATTAACACGTATAGGCGTTACTTGAGACAATAGGTGTTCGTAGCAAGAATTATCGGGCGCAAATCATAGATCTCAAAACGCGGCGAACCGACCAGGATAACGTGGCCGGTGCATCGTGAAGTTCCGTCGCTGCGTTCTCATTACGGAACCGACGAGAATGGGCCTTGTATCCGAAAGTCTGTAGCTAATGTTTGTAAAGGTTTGGGATTGCCACGCCTAGCTAGCCAGGTCAGAACACGGAGGCGAGACTACCAAGCTACGAACAAGT"

func CountDNA(s string) (int, int, int, int) {
	A, C, G, T := 0, 0, 0, 0

	for _, v := range s {
		switch v {
		case 'A':
			A++
		case 'C':
			C++
		case 'G':
			G++
		case 'T':
			T++
		}
	}

	return A, C, G, T
}

func main() {
	A, C, G, T := CountDNA(sample_s)
	fmt.Printf("%d %d %d %d\n", A, C, G, T)
}
