package main

import (
	"fmt"
	"strings"
)

func main() {
	rna:= map[string]string{"UUU":"F","CUU":"L","AUU":"I","GUU":"V",
							"UUC":"F","CUC":"L","AUC":"I","GUC":"V",
							"UUA":"L","CUA":"L","AUA":"I","GUA":"V",
							"UUG":"L","CUG":"L","AUG":"M","GUG":"V",
							"UCU":"S","CCU":"P","ACU":"T","GCU":"A",
							"UCC":"S","CCC":"P","ACC":"T","GCC":"A",
							"UCA":"S","CCA":"P","ACA":"T","GCA":"A",
							"UCG":"S","CCG":"P","ACG":"T","GCG":"A",
							"UAU":"Y","CAU":"H","AAU":"N","GAU":"D",
							"UAC":"Y","CAC":"H","AAC":"N","GAC":"D",
							"UAA":"","CAA":"Q","AAA":"K","GAA":"E",
							"UAG":"","CAG":"Q","AAG":"K","GAG":"E",
							"UGU":"C","CGU":"R","AGU":"S","GGU":"G",
							"UGC":"C","CGC":"R","AGC":"S","GGC":"G",
							"UGA":"","CGA":"R","AGA":"R","GGA":"G",
							"UGG":"W","CGG":"R","AGG":"R","GGG":"G"}
	
//	s := "ATGGTCTACATAGCTGACAAACAGCACGTAGCAATCGGTCGAATCTCGAGAGGCATATGGTCACATGATCGGTCGAGCGTGTTTCAAAGTTTGCGCCTAG"
//	instrons := []string{
//		"ATCGGTCGAA",
//		"ATCGGTCGAGCGTGT",
//	}
	
	s := "ATGTATGAACGCTCGTATTTTTTCCCCGTAGATCAATTCGGGGCCAATCGCTCCACTGCTAACCGACATAATCTTTGGGAGCATCACGCAGATGACAACCACCGAAGTCAAGAGCGGGGCGTGCACAAGTGGTCTCGATCGCATCCGAAAGAACGCGGTGGTATCTTTATCCACCGGGCCCCTCGACGCCTAACTACCTGCTATTTAATCTTTCTTTGCTGGATCACTGAATAGCCTGTCCCCGCAACGGAGGTATACGAAACGGCGTATTACGAACCTCGAAATAGCCTCGTATTACAAAATGCCAATGATTCATTAGCAAATCGAGAGACTTATGGCAAATATGCCGATTCCAAGTGAACGACCACCCGCGGGACGTTGGCCTCGTACTACATGCAGTGGCCGAGTTCGTATTTAACACCAGTGTTGCACCTTGATACTCTTTCGCGATAGACTGCAAAACTTCTCCTGTGTTCTCCTCGTACCCGGGAAAGAACGGATGCTGAAACGCGCTATTGGTTATTCGGTTGATGCACGAGTACACCTGCGCACACGTCTGGTGAGACAGTGTCGGAAAGTGTTTGGCAGAATTATTTGTTATGCCAAAGTACTGGAAACTTAACTGTTGTTCCCTGATACAGAGACGGTGAAATCCGTATCTGGACCCTCATTCTTCTTCGACTCTGCGGTAACGCGGCGGGTTGTATGTCCCTATATACAATAGTGTAACGACGAAGATTGCTAGTGAGACGGCCAACAGTTCCGGCCGTGTCAAAGCATCACCCGCTGTATCCTAGGGTCGTGATCTTCGCAACTGCAAACTCAGAAGCCAAATGCGCACACCTGCTCGGAGCGGATCTGCTATTATAGAGGTACCGGTTTCCGCAAGTTCGATTAACTCGCTACTTCTGGGTGAAGAGCACATCCCGGTACCTGCGTACCAGAGGCCATTAGATTCCAAGCAGATAGTAGGGAGTTCTGGTTTTGGGAGATAA"
	instrons := []string{
		"GGAGCGGATCTGCTATTATAGAGGTACCGGTT",
		"GACTCTGCGGTAACGCGGCGGGTTGTATGTCCCT",
		"GGAAACTTAACTGTTGTTCCCTGATACAGAG",
		"CCAGTGTTGCACCTTGATACTCTTTCGCGATAGACTGCAAAA",
		"CACCCGCGGGACGTTGGCCTCG",
		"TTCGGTTGATGCACGAGTACACCTGCGCACACG",
		"CCTGCGTACCAGAGGCCATTAGATTCCAAG",
		"AAGATTGCTAGT",
		"GAAATAGCCTCGTATTACAAAATGCCAATGA",
		"ATCCGAAAGA",
		"CGACATAATCTTTGGGAGCATCACG",
		"GTATCCTAGGGTCGTGATCTTCGCAACTGCAAAC",
		"TTTAATCTTTCTTTGCTGGATCACTGAATAGCCTGTCCCCG",
	}
	
	for _,ins := range instrons {
		s = strings.Replace(s,ins,"",-1)
	}
	s = strings.Replace(s,"T","U",-1)
	
	r:=""
	for {
		exon := rna[s[:3]]
		if exon == "" {break}
		r += exon
		s = s[3:]
	}
	
	fmt.Println(r)
	
//	fmt.Printf("%t\n","MVYIADKQHVASREAYGHMFKVCA"==r)
}

